# Generated by Django 3.2 on 2022-07-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='number_host',
            field=models.IntegerField(blank=True, choices=[(1, 'One day'), (2, 'Two days'), (3, 'Three days')], default=1, null=True, verbose_name='Nº of days'),
        ),
    ]
