# Generated by Django 3.2 on 2022-07-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_reservation_number_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
