# Generated by Django 3.2 on 2022-07-03 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_alter_reservation_checkin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='rooms',
        ),
    ]
